POST http://localhost:8080/excel/stl/crawling/list
Content-Type: application/json

[
  {
    "value": "20251031",
    "id": "regDate",
    "oper": "eq",
    "operSep": "",
    "priority": 1
  },
  {
    "value": "20251031",
    "id": "regDate",
    "oper": "eq",
    "operSep": "",
    "priority": 1
  }
]